language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: KVXuJvsaZlS4GuR5mgQBECcNQ6pOiRmEy+J00IoodsOF6/hBHCkifmxiXM7WYhjh2uMVX3a06G5A9bIVNB8RC6V0g3F5zMx/wUmYpiE8tA3pfxPZW1oV6eXxUoO2HBHozjyQA8fhl7UyFVkIkwPcAYY7mpPciygM9noOOex6SEqe2Dq0IMMAx/yMw8L9Mwq9ZDnRhEj7RBIeU9G7m/kOsmdCauRStFkRDUzy6iXhJqPFGxUmoHyC4YpJwb3fFxAqSA0e57PRiBsq4t1nEQADV1QFchyXSQTmIoKgEhyD/fhnHS6NKq0/paT3VIdGbIOZHroRl98Kc5voS4X32GkjPPp4V9cQR7OXlvNRqU2Grkc7tzbBUtX5cJPzajK1zEYe2qWjtptgmGZLY543kMRQf2XSlVm7+0Bj6xuoybkXIePXzgmYLS3A8wYk1WcXl4FkHfvNMjqZD1KA+9Fy2f0nPmsI2kSlAadpeB8m+0s7CP0jL20lGcewKu776BlZPNZa51prMxwgOFE/MMARdFwSP/em2dnZDbH9iKfTuZQ6CCgh+WjOndZC0PEZs7ofnzDqlpLoOCvC7tzrrv+flhlRzKBznPhaHpwrHtfaj+QQNTcicuAWvjJ2TnaGmAo0tnA84BoQv09tRmipHPskobUV6MnLdP+lpb1iR35M6N5OdOY=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
